name: number_to_character
description: A new Flutter package is build to convert number to text.
version: 0.0.12
homepage: https://github.com/binSaed/number_to_character

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0